name: Python application build and test only

on:
  push:
    branches: [ build_only ]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install unittest
        pip install mysql
        pip install mysql.connector
        pip install mock
        
     - name: Install mysql server
       run: |
        sudo apt update
        sudo apt install mysql-server
        
     - name: run unittest
       run: |
        # calling via python will also add the current directory to sys.path
        python -m unittest test_service.py
