name: Python application build and test only

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install unittest2
        pip install mysql
        pip install mysql.connector
        pip install mock
        pip install fastapi
        pip install pydantic
        
        
       
        sudo apt update
        wget https://dev.mysql.com/get/mysql-apt-config_0.8.14-1_all.deb
        sudo dpkg -i mysql-apt-config_0.8.14-1_all.deb
        sudo apt update
        sudo apt install mysql-server
        sudo service mysql stop
        sudo mysqld_safe --skip-grant-tables
        mysql -u root 
        UPDATE mysql.user SET Password=PASSWORD('') WHERE User='root';
        sudo mysql start
        
    -  name: run unittest
       run: |
        # calling via python will also add the current directory to sys.path
        cd app/
        python -m unittest test_service.py
